### TOPOLOGY SETUP
IPBase: 10.0.0.0/8

# Define tests which will be applied in the system after clicked on button Test topology
# [test_name] [expected_output]
topologyTests:
  - ping_topology_test 10.0.0.1
  - ping_topology_test 10.0.0.2
  - username_test pepa

### VIRTUAL NETWORK SETUP
networkTemplate: topology1

# Mininet switches
networkSetup:
  - --mac # ID = MAC
  - -v info # info, debug, output
#  - --test pingall # pingall, pingpair, iperf, iperfudp
#  - --innamespace # put hosts in their own namespaces; controllers and switches are default in theis own namespaces


### SDN CONTROLLERS SETUP (SWITCHES AND PACKAGES)
Pox:
  - --verbose
  - py
  - samples.pretty_log
  - forwarding.l2_learning
  - openflow.of_01 --port=6653

Ryu:
  - --verbose
  - --observe-links
  - ryu/app/gui_topology/gui_topology.py
  - ryu/app/simple_switch_13.py
